### ISSUE TITLE
The Image don't trigger Build on certain generation

### ISSUE THREAD

**Issue by smile37773** [pivotal/kpack#1022] opened 2022-08-30 08:59 UTC
We met an error that the image doesn't trigger a new build on a certain generation.

Here are the details, image generation 138 didn't trigger a build.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/34502364/187394775-8352f5a0-561b-4ea5-a2bd-1c75e3a40dbb.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/34502364/187394802-42723463-81e8-4ab8-af06-cae0fea84ca8.png)

We see an error in kpack-controller logs:
![image](https://user-images.githubusercontent.com/34502364/187394406-d05a6743-c139-47da-8fd7-d3651e2436c0.png)

Is that expected? If the answer is Yes, could you please tell me how to avoid this and get the correct build according to a certain image generation?

**Comment by tylerphelan** [comment] 2022-08-30 14:29
@smile37773 
This likely represents a race condition in the k8s api and is expected behavior. It is not uncommon for changes to be made to a resource before a reconciler is able to save its own changes to the resource which results in `the object has been modified, please apply your changes to the latest version and try again` error. The declarative nature of kpack and the k8s api make these errors non-critical as they will eventually be reconciled correctly on the next reconciliation loop as it will just retry.

A resource `generation` will be incremented by k8s for each write to a resource `spec` so it is possible that multiple `Image` resource spec is updated twice before a `Build` resource is able to be scheduled resulting in the skipped `image.kpack.io/imageGeneration`. Using this label will give the correct `generation` of the `Image` resource used to create the `Build`

**Comment by smile37773** [comment] 2022-08-31 03:26
@tylerphelan  For our usage, users can update the image again before the previous build is completed.  The latest version image is not what the user wants. Do you have a plan to resolve the race condition?

**Comment by tylerphelan** [comment] 2022-08-31 15:31
@smile37773 I just tested this and it is behaving as expected.

Due to kubernetes declarative api, the `image.kpack.io/imageGeneration` on the `Build` resource will always be the generation of the `Image` resource at the time that the `Build` resource was created.

If there are multiple updates to the image resource before a previous `Build` resource is finished, the latest configuration of the `Image` resource will be used.

> The latest version image is not what the user wants.
Could you elaborate on this use case?

**Comment by smile37773** [comment] 2022-09-01 01:58
@tylerphelan  
![kpack race condition drawio](https://user-images.githubusercontent.com/34502364/187815826-8d5d1cd0-ab94-41d9-b064-222b35340c8b.png)
 
The latest build 2 we get is not the build we want. Because it contains update 2.  What we want is the build 2 triggered by image generation 2. 

The key point is that image generation 2 has been skipped and didn't trigger a build.

**Comment by tylerphelan** [comment] 2022-09-01 15:15
@smile37773 
A image generation will only get skipped if the update to the `Image` resource occurred before a running `Build` completed.

The only way to ensure every image generation produces a build would be to run builds concurrently which we can't do for a few reasons:
- Mainly because builds are async and may complete out of order causing writes to the tag and `latestImage` field to be out of sync
- Shared cache reads/writes can be troublesome
- It violates the declarative model

**Comment by matthewmcnew** [comment] 2022-09-01 19:32
@smile37773 If it is needed to schedule an individual build with each discrete updated configuration the build resource should be used directly. The image resource is designed to only schedule the most recent specified configuration.

**Closed by matthewmcnew** 2022-09-01 19:32 UTC
