### ISSUE TITLE
Investigate support for ECR

### ISSUE THREAD

**Issue by mgibson1121** [pivotal/kpack#511] opened 2020-09-28 14:47 UTC
**What:**  Investigate if kpack can reliably publish images in an ECR registry.

**Why:**  Every few months the team receives a question about ECR support and our answer leaves room to be desired.  We've typically told these people that we are unsure of how kpack and the registry will behave given that ECR doesn't support the V2 Docker Registry API.  We've recently had two companies interested in using kpack ask about ECR support.

**Comment by tsalm-pivotal** [comment] 2020-09-28 18:30
FYI Based on the FAQs [here]( https://aws.amazon.com/ecr/faqs/) Amazon ECR supports the Docker Registry V2 API specification. 
Nevertheless, it's not possible to use ECR as a registry with kpack without workarounds because of the [registry authentication](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth) (authorization tokens are only valid for 12 hours).

**Comment by matthewmcnew** [comment] 2020-10-02 15:23
After testing this, I have confirmed that ECR does supports the v2 docker registry api. However, as @tsalm-pivotal  points out the short lived registry authentication (12 hours) is quite prohibitive to using kpack with ECR in a production setting.

**Comment by jim80net** [comment] 2020-10-04 04:38
For those that encounter this issue and would like to apply a workaround, I can confirm that the following works: https://stackoverflow.com/questions/54128535/kubernetes-cronjob-and-updating-a-secret

**Comment by matthewmcnew** [comment] 2020-10-05 14:02
@jim80net That's smart. Thanks for sharing!

**Comment by matthewmcnew** [comment] 2022-06-30 17:55
Closing with support for ECR/EKS cred helpers.

**Closed by matthewmcnew** 2022-06-30 17:55 UTC

**Comment by tcdowney** [comment] 2022-07-14 15:38
@matthewmcnew do you have a link to the commit or PR that added ECR/EKS support?

**Comment by matthewmcnew** [comment] 2022-07-14 16:29
The most recent release of kpack, https://github.com/pivotal/kpack/releases/tag/v0.6.0 added support for utilizing EKS IAM roles on EKS service account to use ECR via ECR's credential helpers: https://github.com/pivotal/kpack/pull/959

**Comment by matthenry87** [comment] 2023-04-06 22:02
> > The most recent release of kpack, https://github.com/pivotal/kpack/releases/tag/v0.6.0 added support for utilizing EKS IAM roles on EKS service account to use ECR via ECR's credential helpers: #959
> 
> Is there any documentation on this? I cannot seem to find anything after a few hours of searching. I am looking to use EKS to build images with kpack and push to ECR - so I assume I need to specify which service account kpack should use

Did you ever find this answer? I'm trying to create a docker secret with below contents, but it's giving me an error related to AWS credentials. I am using IAM Roles for Service Accounts.
```
{
	"credsStore": "ecr-login"
}
```
```
❯ kc create secret docker-registry ecr -n kpack --from-file .dockerconfigjson

Unable to locate credentials. You can configure credentials by running "aws configure".
error: failed to create secret Post "https://CF1F8370EFDB835CA6BAEA8B527AAB01.gr7.us-east-2.eks.amazonaws.com/api/v1/namespaces/kpack/secrets?fieldManager=kubectl-create&fieldValidation=Strict": getting credentials: exec: executable aws failed with exit code 253
```

**Comment by matthenry87** [comment] 2023-04-09 20:39
Also wondering about how to get this working. I've been digging for a few days without success. I've added the following to a secret and referenced it from my serviceaccount:

```
.dockerconfigjson: "{\n\t\"credsStore\": \"ecr-login\"\n}\n"
```

Still not working. Is there documentation anywhere for kpack's ECR credential helper support?
