### ISSUE TITLE
Large buildpack metadata exceeds 16MB and causes K8S nodes to go down

### ISSUE THREAD

**Issue by chriddyp** [pivotal/kpack#893] opened 2021-11-26 22:42 UTC
Hi folks! We're reopening this issue: https://github.com/pivotal/kpack/issues/843

We've discovered another group that ran into this with a more detailed investigation: https://githubmemory.com/repo/paketo-buildpacks/spring-boot/issues/80:

> The reason for this was quite obvious once we have investigated the issue. The buildpack puts the a file listing of the app code as metadata to the resulting image label io.buildpacks.lifecycle.metadata. As a result of this, the image and later then the K8s pod metadata get quite huge. In our case the image metadata grows to around 3.2MB in size. When we now run multiple such pods on the same K8s node the overall metadata of all pods can get quite huge. And exactly this is the reason for forcing the K8s node to go down.

> So, this is my current understanding what leads to this situation: The K8s kubelet component responsible for retrieving the current state of all containers (part of PLEG) uses gRPC to communicate with the container runtime. This gRPC has a maximum message size of 16MB. If now the metadata of all containers on a node grow beyond this 16MB limit, kubelet can't query the state of its containers any more, finally leading to an unusable K8s node. The error message that we see in this situation is:

```
... code = ResourceExhausted desc = grpc: trying to send message larger than max (21922673 vs. 16777216)
```

The other community that ran into this was using the `spring-boot` buildpack and fixed it by updating the metadata labels in the buildpack: https://github.com/paketo-buildpacks/spring-boot/pull/83

In our case, we've been using the Python buildpacks. We're not sure how the metadata in that buildpack is being constructed and whether or not it could be fixed in that buildpack or should be fixed in `kpack` itself.

Thanks for the help!

**Comment by chriddyp** [comment] 2022-02-03 17:10
It looks like kpack 0.5.0 stores this data in a layer instead of an annotation. I'm curious if that change was intended to fix this issue? 

> Buildpacks that utilize Buildpack API 0.7 will use the new SBOM format written as a layer instead of an image label as documented here.

**Comment by matthewmcnew** [comment] 2022-02-07 23:18
Yes, kpack provides support for using the new [sbom support](https://github.com/buildpacks/rfcs/blob/main/text/0095-sbom.md) in the [0.7 Buildpack api](https://buildpacks.io/docs/reference/spec/migration/buildpack-api-0.6-0.7/) which writes the sbom content to a layer in the image instead of the image label. This change was intended to migrate buildpacks and the buildpack community from writing prohibitively large BOM labels.

**Comment by matthewmcnew** [comment] 2022-02-07 23:19
Because kpack is merely executing the cloud native buildpacks specification and this will ultimately be fixed in buildpack implementations I am going to close this issue.

**Closed by matthewmcnew** 2022-02-07 23:19 UTC

**Comment by tylerphelan** [comment] 2022-09-23 16:48
For future reference: using containerd as a cri will fix this issue. containerd is now available on eks.
