### ISSUE TITLE
Bug when rebasing onto a new stack

### ISSUE THREAD

**Issue by RadiatorSpring** [pivotal/kpack#948] opened 2022-04-07 07:29 UTC
Hi,
We are using kpack release 0.5 with stack paketobuildpacks/build:base-cnb and paketobuildpacks/run:base-cnb. 
When there is a new release of said buildpacks kpack tries to rebase on it and even though it succeeds it continues creating containers for this rebase ad infinitum. The only fix is to recreate the ClusterStack resource
```
rebase Build reason(s): STACK
rebase STACK:
rebase     - sha256:38199b888e33bed03b98bfed20a091733f502c33ced1a6660ed5c92ed82308ea
rebase     + sha256:099a4fd96ffbc2a54d98594a99c1a1dbe6c2dc8e5cec60d0f45fcfcd7dd353d9
rebase Loading secret for "kneo-sofia.docker.repositories.cloud.sap" from secret "image-registry-credentials" at location "/
var/build-secrets/image-registry-credentials"
stream logs failed container "completion" in pod "185e35c7-2d8f-4934-b03f-562c4fa91106-build-24-build-pod" is waiting to sta
rt: PodInitializing for c8074786-f3ed-43f3-8ea3-a12b607dbc44/185e35c7-2d8f-4934-b03f-562c4fa91106-build-24-build-pod (comple
tion)
stream logs failed container "completion" in pod "185e35c7-2d8f-4934-b03f-562c4fa91106-build-24-build-pod" is waiting to sta
rt: PodInitializing for c8074786-f3ed-43f3-8ea3-a12b607dbc44/185e35c7-2d8f-4934-b03f-562c4fa91106-build-24-build-pod (comple
tion)
rebase *** Images (sha256:f00f6fab9ef2381368661d6ca182ce7b987308ae0a023e5b16f20c074522c1a7):
rebase       kneo-sofia.docker.repositories.cloud.sap/poc/kneo/neonk8s/kpack/beta/185e35c7-2d8f-4934-b03f-562c4fa91106
rebase       kneo-sofia.docker.repositories.cloud.sap/poc/kneo/neonk8s/kpack/beta/185e35c7-2d8f-4934-b03f-562c4fa91106:b24.2
0220407.070502
rebase
rebase *** Digest: sha256:f00f6fab9ef2381368661d6ca182ce7b987308ae0a023e5b16f20c074522c1a7
stream logs failed container "completion" in pod "185e35c7-2d8f-4934-b03f-562c4fa91106-build-24-build-pod" is waiting to sta
rt: PodInitializing for c8074786-f3ed-43f3-8ea3-a12b607dbc44/185e35c7-2d8f-4934-b03f-562c4fa91106-build-24-build-pod (comple
tion)
Stream closed EOF for c8074786-f3ed-43f3-8ea3-a12b607dbc44/185e35c7-2d8f-4934-b03f-562c4fa91106-build-24-build-pod (rebase)
completion Build successful
Stream closed EOF for c8074786-f3ed-43f3-8ea3-a12b607dbc44/185e35c7-2d8f-4934-b03f-562c4fa91106-build-24-build-pod (completi
on)
```

**Comment by matthewmcnew** [comment] 2022-04-13 21:06
Duplicate of https://github.com/pivotal/kpack/issues/641.

**Closed by matthewmcnew** 2022-04-13 21:06 UTC
